name: "WorldProtection"
main: "org.xiaomu.WorldProtection.WorldProtection"
author: "xiaomu18"

website: "https://github.com/StarCodeClub/WorldProtection"
version: "1.3.0"
api-version: "1.21"
description: "灵活的世界保护插件，支持层次化配置和权限系统"
folia-supported: true

commands:
  wp:
    usage: "/wp help"
    description: "WorldProtection 的主命令"
    permission: "wp.admin"
    permission-message: "<black><bold>[WP]</bold> <red>你没有权限这样做.</red>"

permissions:
  wp.admin:
    description: "允许使用 /wp 命令"
    default: op
  wp.bypass.*:
    description: "绕过所有世界保护"
    default: op
    children:
      wp.bypass.*.anti-world-edit: true
      wp.bypass.*.anti-pvp: true
      wp.bypass.*.anti-player-enter: true
      wp.bypass.*.anti-block-interaction: true
      wp.bypass.*.anti-attack-entity: true
      wp.bypass.*.anti-entity-interaction: true